site_name: LiquidHub
repo_url: https://github.com/insales/insales-docs-source/

theme:
  name: 'material'
  features:
    - navigation.sections
    - navigation.indexes


extra_css:
  - css/extra.css

extra_javascript:
  - js/jquery.min.js
  - js/extra.js

nav:
  - index.md
  - 4 поколение:
    - Шаблон:
      - 4 поколение/Шаблон/index.md
      - 4 поколение/Шаблон/layout.liquid.md
      - 4 поколение/Шаблон/messages.json.md
      - 4 поколение/Шаблон/settings.json.md
      - 4 поколение/Шаблон/setup.json.md
    - Виджеты:
      - 4 поколение/Виджеты/snippet.liquid.md
      - 4 поколение/Виджеты/snippet.scss.md
      - 4 поколение/Виджеты/snippet.js.md
      - 4 поколение/Виджеты/messages.md
      - 4 поколение/Виджеты/settings_form.md
      - 4 поколение/Виджеты/settings_data.md
      - 4 поколение/Виджеты/setup.md
      - 4 поколение/Виджеты/preview.md
      - 4 поколение/Виджеты/info.md
      - 4 поколение/Виджеты/index.md

      - Примеры:
        - 4 поколение/Виджеты/Примеры/SimpleWidgetType.md
        - 4 поколение/Виджеты/Примеры/block_list_widget_type.md
    - Иконки:
      - 4 поколение/Иконки/icons_editor.md
      - 4 поколение/Иконки/icons_theme.md
    - 4 поколение/core.css.md
  - common.v2.js:
    - common.v2.js/1readme.md
    - common.v2.js/2Products.md
    - Опции:
      - common.v2.js/ui-accessories/README.md
      - common.v2.js/ui-accessories/product.md
      - common.v2.js/ui-accessories/cart.md
    - common.v2.js/3Cart.md
    - common.v2.js/4AjaxSearch.md
    - common.v2.js/5Compare.md
    - common.v2.js/6FavoritesProducts.md
    - common.v2.js/7EventBus.md
    - common.v2.js/8ajaxAPI.md
    - AJAX-товары:
      - common.v2.js/ajax-products/README.md
      - common.v2.js/ajax-products/ui-ajax-product.md
      - common.v2.js/ajax-products/ui-ajax-products.md
    - common.v2.js/9ui-ajax-filters.md
    - common.v2.js/10ui-feedback.md
    - common.v2.js/ui-reviews.md
    - common.v2.js/ui-comments.md
    - common.v2.js/ui-quick-checkout.md
    - common.v2.js/11ui-trigger-events.md
    - common.v2.js/12Template.md
    - common.v2.js/13InSalesUI.md
    - common.v2.js/14Shop.md

  - Примеры работы с данными магазина:
      - images_for_options:
        - Примеры работы с данными магазина/images_for_options/README.md
      - reCAPTCHA:
        - Примеры работы с данными магазина/reCAPTCHA/README.md
        - Примеры работы с данными магазина/reCAPTCHA/aroma2.md
        - Примеры работы с данными магазина/reCAPTCHA/commonjs.v2.md
        - Примеры работы с данными магазина/reCAPTCHA/dotstore.md
        - Примеры работы с данными магазина/reCAPTCHA/fleur.md
        - Примеры работы с данными магазина/reCAPTCHA/prezent.md
        - Примеры работы с данными магазина/reCAPTCHA/recaptcha-common.md
        - Примеры работы с данными магазина/reCAPTCHA/template_without_commonjs.md
        - Примеры работы с данными магазина/reCAPTCHA/v3.md
        - Примеры работы с данными магазина/reCAPTCHA/z.InSales.md
      - site_currencies:
        - Примеры работы с данными магазина/site_currencies/index.md
  - InSales API:
    - InSales API/01 readme.md
    # - InSales API/02 Подключение внешнего способа оплаты (для разработчиков интеграций).md
    # - InSales API/03 Получение только изменившихся данных.md
    # - InSales API/04 API для работы с частичными скидками.md
    # - InSales API/05 InSales API - Widgets.md
    # - InSales API/06 InSales API - Счета приложения.md






extra:
  search:
    language: 'en, ru'

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
