site_name: LiquidHub
repo_url: https://github.com/insales/insales-docs-source/

theme:
  name: 'material'

extra_css:
  - css/extra.css

extra_javascript:
  - js/jquery.min.js
  - js/extra.js


extra:
  search:
    language: 'en, ru'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - codehilite
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
